apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova-bot

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - gateway-deployment.yaml
  - feed-worker-deployment.yaml
  - api-worker-deployment.yaml
  - api-service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: nova-feed-bot
