import type { PricingPlanConfig } from './PricingCard';

export const PLANS_CONFIG: PricingPlanConfig[] = [
  {
    id: 'free',
    badgeVariant: 'neutral',
    titleKey: 'premium.freeTitle',
    priceMonthlyKey: 'premium.freePriceMonthly',
    priceYearlyKey: 'premium.freePriceYearly',
    descKey: 'premium.freeDesc',
    featureKeys: [
      'premium.freeFeature1',
      'premium.freeFeature2',
      'premium.freeFeature3',
      'premium.freeFeature4',
    ],
    ctaVariant: 'secondary',
    ctaKey: 'premium.freeCta',
    isBuyable: true,
  },
  {
    id: 'starter',
    interactive: true,
    badgeVariant: 'neutral',
    titleKey: 'premium.starterTitle',
    priceMonthlyKey: 'premium.starterPriceMonthly',
    priceYearlyKey: 'premium.starterPriceYearly',
    descKey: 'premium.starterDesc',
    featureKeys: [
      'premium.starterFeature1',
      'premium.starterFeature2',
      'premium.starterFeature3',
      'premium.starterFeature4',
      'premium.starterFeature5',
    ],
    ctaVariant: 'secondary',
    ctaKey: 'premium.starterCta',
    isBuyable: true,
  },
  {
    id: 'professional',
    glow: 'blue',
    interactive: true,
    badgeVariant: 'online',
    titleKey: 'premium.professionalTitle',
    pillKey: 'premium.professionalBadge',
    priceMonthlyKey: 'premium.professionalPriceMonthly',
    priceYearlyKey: 'premium.professionalPriceYearly',
    descKey: 'premium.professionalDesc',
    featureKeys: [
      'premium.professionalFeature1',
      'premium.professionalFeature2',
      'premium.professionalFeature3',
      'premium.professionalFeature4',
      'premium.professionalFeature5',
    ],
    ctaVariant: 'primary',
    ctaKey: 'premium.professionalCta',
    isBuyable: true,
  },
  {
    id: 'ultimate',
    interactive: true,
    badgeVariant: 'tier',
    titleKey: 'premium.ultimateTitle',
    pillKey: 'premium.ultimateBadge',
    priceMonthlyKey: 'premium.ultimatePriceMonthly',
    priceYearlyKey: 'premium.ultimatePriceYearly',
    descKey: 'premium.ultimateDesc',
    featureKeys: [
      'premium.ultimateFeature1',
      'premium.ultimateFeature2',
      'premium.ultimateFeature3',
      'premium.ultimateFeature4',
      'premium.ultimateFeature5',
    ],
    ctaVariant: 'primary',
    ctaKey: 'premium.ultimateCta',
    isBuyable: true,
  },
];

