import type { PricingPlanConfig } from './PricingCard';

export const PLANS_CONFIG: PricingPlanConfig[] = [
  {
    id: 'free',
    badgeVariant: 'neutral',
    titleKey: 'premium.freeTitle',
    priceKey: 'premium.freePrice',
    pricePeriodKey: 'premium.freePricePeriod',
    descKey: 'premium.freeDesc',
    featureKeys: [
      'premium.freeFeature1',
      'premium.freeFeature2',
      'premium.freeFeature3',
      'premium.freeFeature4',
    ],
    ctaVariant: 'secondary',
    ctaKey: 'premium.freeCta',
  },
  {
    id: 'plus',
    glow: 'blue',
    interactive: true,
    badgeVariant: 'online',
    titleKey: 'premium.plusTitle',
    pillKey: 'premium.plusBadge',
    priceKey: 'premium.plusPrice',
    pricePeriodKey: 'premium.plusPricePeriod',
    descKey: 'premium.plusDesc',
    featureKeys: [
      'premium.plusFeature1',
      'premium.plusFeature2',
      'premium.plusFeature3',
      'premium.plusFeature4',
      'premium.plusFeature5',
    ],
    ctaVariant: 'primary',
    ctaKey: 'premium.plusCta',
  },
  {
    id: 'master',
    glow: 'purple',
    interactive: true,
    badgeVariant: 'tier',
    titleKey: 'premium.masterTitle',
    priceKey: 'premium.masterPrice',
    pricePeriodKey: 'premium.masterPricePeriod',
    descKey: 'premium.masterDesc',
    featureKeys: [
      'premium.masterFeature1',
      'premium.masterFeature2',
      'premium.masterFeature3',
      'premium.masterFeature4',
      'premium.masterFeature5',
    ],
    ctaVariant: 'secondary',
    ctaKey: 'premium.masterCta',
  },
];
